/* HIGHLY DIVISIBLE TRIANGULAR NUMBER
=======================================
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

Date : 30 Sep 2016
Duration: 20 min
*/

#include <iostream>
#include <math.h>
using namespace std;

int countDivisors(const int num)
{
	int count=0;
	int mid = sqrt((float)num);

	for (int i=1; i<=mid; i++)
	{
		if (num%i == 0)
		{
			count = (i*i == num) ? count+1 : count+2;
		}
	}

	return count;
}


int main()
{
	const int target = 500;
	int curAdder=2, curTriNum=1, curDivisorCount=0;

	while (countDivisors(curTriNum) <= 500) 
	{
		curTriNum += curAdder;
		curAdder++;
	}

	cout << "The value of the first triangle number to have over five hundred divisors is " << curTriNum << endl;
	return 0;
}